settings:
    servers:
        wandel:
            host: 0.0.0.0
            port: 1337
            wandel_1: "http://www.wandel-restaurant.de/restaurants/bernhard-weiss-str/wandel8/start.html"
            slack_token: ~
