settings:
    servers:
        wandel:
            host: 0.0.0.0
            port: 1337
            menu_1: # wandel tends to change their file format...
                - https://www.wandel-restaurant.de/fileadmin/dms-Wandel-Restaurants/Restaurants/Mitte/Speiseplaene_Wandel_Berlin_Mitte/Speiseplan_Wandel_Berlin_Mitte_KW_%s_%s.pdf
            slack_token: ~
